# Generated by Django 5.1.1 on 2024-09-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageshare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='created_by',
            new_name='liked_by',
        ),
    ]
